### ISSUE TITLE
Deletes property if not followed by semicolon

### ISSUE THREAD

**Issue by kalligator** [hdemirchian/CSSFormat#4]
Ommiting the ending semicolon after the last property is valid css syntax, however this plugin completely deletes the property in this case.

**Comment by hamishcampbell** [comment]
Yep, this is particularly bad if you've already run your css through a pre-processor like LESS that strips the ending semi-colons. Formatting a several kb stylesheet produced a single html tag :-1:

**Comment by y0n3r** [comment]
This is still a major issue. Judging by the ticket date, I don't think anyone is going to fix it. I'm removing the package from Sublime.

**Comment by hdemirchian** [comment]
This bug is fixed.
Sorry for taking so long to fix it.  I've been supper busy.
Thanks for your comments.
